### ISSUE TITLE
Доступность объекта $zoomx в шаблонах

### ISSUE THREAD

**Issue by Semdevmaster** [sergant210/ZoomX#1]
При включенной настройке zoomx_include_modx, которая должна предоставить доступ к двум объектам в шаблонах:
$modx и $zoomx, второй всегда равен null, поэтому, нет возможности вызвать какой либо метод этого объекта, например сниппет через $zoomx->runSnippet() или $zoomx->runFileSnippet()

**Comment by sergant210** [comment]
Исправлено в версии 3.2.0.
