### ISSUE TITLE
Не работает кэш Smarty в обычных шаблонах, обычные шаблоны парсятся несколько раз

### ISSUE THREAD

**Issue by ldrshv** [sergant210/ZoomX#12]
Здравствуйте, кэш Smarty не работает в обычных шаблонах.
Ещё если вызвать {$modx->log(1, $modx->resource->pagetitle)} во включенном в обычный шаблон через include .tpl файле, в лог выводится сначала текущая страница, а потом 404.
Для решения придумал такой костыль: https://modx.pro/development/22757, но хотелось бы, чтоб всё работало из коробки)

**Comment by sergant210** [comment]
Кэширование обычных шаблонов добавил в новой версии.
Получить ошибку с двойным выводом не смог.
