### ISSUE TITLE
 The magic method Zoomx\Service::__wakeup() must have public visibility

### ISSUE THREAD

**Issue by biz87** [sergant210/ZoomX#13]
Начала появляться ошибка
`{core}/components/zoomx/src/Service.php : 599) PHP warning: The magic method Zoomx\Service::__wakeup() must have public visibility`

Рабочее окружение
LEMP 
PHP 7.4.28
modx 2.8.3
ZoomX 3.4.1

**Comment by sergant210** [comment]
Исправлено в новой версии.
