### ISSUE TITLE
Не парсится чанк письма в miniShop при использовании ZoomX

### ISSUE THREAD

**Issue by ldrshv** [sergant210/ZoomX#15]
При использовании ZoomX вместо письма при смене статуса заказа приходит код чанка. Не работает ни Smarty, ни Fenom.
Ещё вместо темы письма приходит [[%ms2_email_subject_new_user]]. То есть не работает стандартный парсер, что странно, учитывая, что ZoomX не инициализируется в mgr.
При оформлении заказа всё нормально, срабатывает Smarty. Fenom на сайте выключен.
Проблему решает плагин:
```php
<?php
switch ($modx->event->name) {
    case 'msOnChangeOrderStatus':
        $corePath = $modx->getOption('zoomx_core_path', null, MODX_CORE_PATH . 'components/zoomx/');
        $modx->setOption('pdoTools.class', 'pdoToolsZoomx');
        $modx->setOption('pdotools_class_path', $corePath . 'pdotools/');
        $modx->setOption('pdoFetch.class', 'pdoFetchZoomx');
        $modx->setOption('pdofetch_class_path', $corePath . 'pdotools/');
        break;
}
```
Но хотелось бы, чтоб без подобных костылей работало)

**Comment by sergant210** [comment]
Оно и логично. ZoomX в mgr не инициализируется, а Fenom отключен.
Дублирует #11.
