### ISSUE TITLE
Идущий из коробки модификатор |resource не работает с кастомными ресурсами

### ISSUE THREAD

**Issue by Semdevmaster** [sergant210/ZoomX#16]
Заметил проблему с ресурсами-товарами из miniShop2, там у ресурсов есть куча полей типа, price, image и.т.д
Так вот на таких ресурсах не работает вывод типа { "price"|resource }, также как и не работает  { $modx->resource->price }
Работает только такой вариант: { $modx->resource->get("price") }
Решил проблему написанием своего модификатора, просто скопировав исходный и заменив там все вызовы полей через метод get(), так вызов { "price"|resource } - заработал.

**Comment by sergant210** [comment]
Принял. Доработаю.

**Comment by sergant210** [comment]
Допилил. Скоро будет.
