### ISSUE TITLE
Не подключается routes.php в своей папке

### ISSUE THREAD

**Issue by ldrshv** [sergant210/ZoomX#19]
Поменял zoomx_config_path на {core_path}app/, перенёс туда routes.php — отображается пустая страница

**Comment by Semdevmaster** [comment]
О проблеме известно, временное решение, просто оставь исходный файл routes.php на своем месте, и создай свой routes.php по тому пути, что указал в конфиге. И всё будет работать, он просто ищет этот файл по дефолтному пути, и пока там может лежать пустышка с таким же названием, а рабочий уже по пути, который указал в сис. настройках

**Comment by catsmeatman** [comment]
> О проблеме известно, временное решение, просто оставь исходный файл routes.php на своем месте, и создай свой routes.php по тому пути, что указал в конфиге. И всё будет работать, он просто ищет этот файл по дефолтному пути, и пока там может лежать пустышка с таким же названием, а рабочий уже по пути, который указал в сис. настройках

А если поставить симлинк с нового конфига на старый, взлетит?

**Comment by sergant210** [comment]
Я же это вроде исправлял 🤔 На выходных постараюсь проверить.

П.С. Я сейчас и на беке и  на фронте (Vue) работаю. Времени свободного остаётся чуть меньше чем 0.

**Comment by sergant210** [comment]
Исправлено. Завтра выйдет обновление.
