### ISSUE TITLE
[ZoomX 3.5] Роутер обрабатывает POST запросы только с путями без слеша в начале, тогда как GET со слешем и без

### ISSUE THREAD

**Issue by Semdevmaster** [sergant210/ZoomX#20]
Допустим есть эндпоинт /ctl - определен в роутере
Режим роутинга ZoomX - смешанный
Ресурса с таким uri - нет
Чтобы пример сработал - запросы и get и post в роутере нужно прописывать сейчас так

![image](https://user-images.githubusercontent.com/2706508/202677436-63dcc796-d265-4d7e-b585-dd4cee4fd076.png)
Так как в противном случае, если для POST запроса также указать /ctl, то ответом будет 404, тогда как на GET запрос - 200
Было бы удобно правила роутинга сделать одинаковыми для всех типов запросов

**Comment by sergant210** [comment]
Подразумевалось, что будет работать и так и так. Проверю.

**Comment by sergant210** [comment]
Исправлено.

**Comment by Semdevmaster** [comment]
Проверил версию 3.5.1 - Ошибка по прежнему актуальна
