### ISSUE TITLE
Некорректная работа 404 ошибки при отключении кэша карты псевдонимов

### ISSUE THREAD

**Issue by Semdevmaster** [sergant210/ZoomX#3]
Суть такая: если кэш карты псевдонимов выключен, то при заходе на неопубликованные страницы всё равно будем получать контент и шаблон этих страниц, при чем при первом обращении возможен код 200, а дальше 404.
Но если сформировать кэш 404 страницы, то всё начнет работать как надо. 
Ощущение, что при отсутствии кэша не происходит запрос на 404 страницу, а ищется только её кэш, и в случае его отсутствия отдается шаблон реальной страницы.

**Comment by sergant210** [comment]
Исправлено в версии 3.3.0-pl.
