### ISSUE TITLE
Получение body при post запросе данных

### ISSUE THREAD

**Issue by alexsoin** [sergant210/ZoomX#4]
## Сценарий:

Отправка `post` запроса с параметрами в `body` ввиде `json` строки и его последующая обработка внутри роута.

## Ожидаемый результат 

Получение данных внутри переменной `$_POST` или через специальный метод.

## Текущий результат

```
NULL
```

## Вариант решения

```php
<?php
$_POST = $_POST ?: json_decode(file_get_contents('php://input' ),true);
```

## Используемое ПО

**postman**

**Comment by sergant210** [comment]
Я так понимаю, что это только для `application/json`?

**Comment by alexsoin** [comment]
Да

**Comment by sergant210** [comment]
В Laravel с этим работают так
```
$request = Request::instance();
$content = $request->getContent();
$json = json_decode($content);
```
Т.е. там тоже автоматически не конвертится.

**Comment by alexsoin** [comment]
Так я и не говорю, что должно автоматически конвертироваться, хорошо было бы, чтобы были методы по типу как в ларавеле `$request->getContent(); `

Для получения данных тела запроса(ну и заголовки можно такимже способом получать). А уже декодить это понятно, что частный случай.

**Comment by Semdevmaster** [comment]
Это же всё уже есть в другом компоненте Сергея - modHelpers
И он прекрасно работает в паре с ZoomX - любые действия с запросом и ответом в контроллерах или роутах - легко!

**Comment by alexsoin** [comment]
@Semdevmaster тоесть вы считаете нормальным подходом для получения только json данных тащить в зависимости ещё один компонент?

**Comment by Semdevmaster** [comment]
Компонент, который по своей сути специализируется на работе с запросами и ответами - Да, я так считаю.
ZoomX - сделан в первую очередь для шаблонизации на Smarty, роутер и всё остальное в нем просто в дагонку.
Я предлагал Сергею сделать единый пакет и объединить функционалы, но пока на это нет времени - поэтому отличным решением пока является установка 2 пакетов. Плохо от этого MODX-у не станет)

**Comment by sergant210** [comment]
@alexsoin  А почему нельзя в плагине на OnMODXInit прописать соответствующий функционал?

**Comment by alexsoin** [comment]
@sergant210 почему нельзя, можно, на тот момент когда я создавал это ишью я считал, что одной из задач данного компонента это создание для modx подхода с работой роутеров и запросов к ним как в популярных фреймворках по типу того же ларавела. 

Сейчас одним из основных видов запросов является отправка в post запрос json данных, поэтому мне казалось логичным, что в компонент было бы не лишним добавить метод для получения таких данных, вместо использования конструкции `json_decode(file_get_contents('php://input' ),true)`, что было бы просто синтаксическим сахаром для более удобочитаемого кода.

Раз обработка запросов это не то, что должно быть в этом компоненте из коробке тогда можно и закрыть это ишью.

**Comment by sergant210** [comment]
> я считал, что одной из задач данного компонента это создание для modx подхода с работой роутеров и запросов к ним как в популярных фреймворках по типу того же ларавела.

Как я писал выше, даже Laravel из коробки это не делает. За это отвечает разработчик. Причина в том, что во время декодирования возможны коллизии и ошибки, для обработки которых нужно писать логику. И она у всех своя.

Я не против добавить такую фичу. Но что делать, если возникнут проблемы при декодировании? Скорее всего нужно дать возможность разработчику по какому-нибудь событию типа OnParseJsonError в плагине обработать эту ошибку и cгенерить корректные данные. Тогда вопрос, не проще ли разработчику сразу написать свою логику в начале запроса?

**Comment by alexsoin** [comment]
> даже Laravel из коробки это не делает

Мы точно про один и тотже Laravel говорим?

![изображение](https://user-images.githubusercontent.com/3787132/202724356-8713e9c8-658b-4c5a-8378-87867964ba24.png)
![изображение](https://user-images.githubusercontent.com/3787132/202724471-a0ca098c-5463-4a30-82bf-6d8c998cb081.png)
![изображение](https://user-images.githubusercontent.com/3787132/202724519-469f4ee3-557f-4882-a161-b7f87215b3b3.png)

**Comment by sergant210** [comment]
Точнее не бывает. $_POST попробуй вывести - сюрприз будет ). А ты делаешь как раз то, а чем я и писал выше.

**Comment by alexsoin** [comment]
Объясни тогда конкретнее в чем я не прав? Для работы с json в laravel надо установить какие-то доп зависимости помимо тех что идут в стоке? Или то что laravel не умеет подставлять в request данные когда запрос приходит в виде json? 

Если посмотришь моё описание в ишью, то там есть такая часть

> или через специальный метод

Так как я не знаю как архитектурно лучше это будет выглядеть в zoomx.

[Вот](https://laravel.com/docs/9.x/requests#retrieving-json-input-values) в доке про это. Я в своём ишью не настаиваю чтобы это было $_POST я только говорю, что было бы хорошо иметь возможность это через какой-то инструмент готовый в компоненте получить. Но как понимаю это без толку, привожу примеры, а ты говоришь, что этого нету в laravel.

**Comment by sergant210** [comment]
> Если посмотришь моё описание в ишью, то там есть такая часть

А если ты сам посмотришь на своё описание, то увидишь вариант решения

```php
<?php
$_POST = $_POST ?: json_decode(file_get_contents('php://input' ),true);
```
Я не знаю, о чем думаешь ты, когда пишешь, но с моей стороны монитора это выглядит как создание массива $_POST автоматически. И никаких вариантов со специальными методами я не вижу. Могу предположить, что если бы ты прислал PR, то он был бы именно таким. И именно про это я и говорил, что Laravel не заполняет автоматом этот массив для json запросов. Обычно мидлварь пишут к этим роутам, если нужен именно $_POST.

А если бы ты посмотрел самое первое [видео](https://youtu.be/w2cC2wMrMy0?t=382), то понял бы для чего задумывался ZoomX изначально. Просто в дальнейшем я файл настроек заменил на роутер для гибкости. Я не планировал делать полноценный фреймворк для работы с MODX. 

Я бы мог и дальше дискутировать, но в таком духе 
> Но как понимаю это без толку

желание моментально отпало. Удачи.
