### ISSUE TITLE
При регистрации файловых плагинов в elements.php нельзя передать пустой массив

### ISSUE THREAD

**Issue by Semdevmaster** [sergant210/ZoomX#6]
В elements.php при регистрации классов плагинов было бы очень удобно иметь возможность оставить пустой массив,
например просто комментируя регистрацию определенных классов в редакторе кода.
Но в таком случае, если в метод registerPlugins не передан хотя бы один класс плагина в консоль валится ошибка.
Пример:
![image](https://user-images.githubusercontent.com/2706508/152119530-960005da-ca61-44ed-b747-7de81435a80a.png)

**Comment by sergant210** [comment]
Исправлено в новой версии.
