### ISSUE TITLE
Свойство $events файлового плагина не может быть пустым массивом

### ISSUE THREAD

**Issue by Semdevmaster** [sergant210/ZoomX#7]
При создании нового файлового плагина и его регистрации, если в свойстве $events пока пустой массив,
то в консоль попадает ошибка. Было бы удобно если в массиве нет активных событий, то это равносильно деактивации плагина. Просто иногда удобнее закомментировать события в массиве, чем указывать $disabled = true, но это чисто мое мнение, сложившееся во время работы с компонентом. Может другим это и не нужно.
Пример:
![image](https://user-images.githubusercontent.com/2706508/152121241-ef3e5a55-fd47-4eec-b752-b6c8c8ccaf3f.png)

**Comment by sergant210** [comment]
Исправлено в новой версии.
