### ISSUE TITLE
Хотелка: Сделать возможность хранить конфиги ZoomX в любой папке

### ISSUE THREAD

**Issue by Semdevmaster** [sergant210/ZoomX#8]
Сейчас настройки компонента позволяют почти все элементы хранить в любой настраиваемой директории проекта, за исключением конфигов ZoomX (routes.php, elements.php)
Если есть возможность сделать доп настройку в компоненте для указания пути хранения этих конфигов

**Comment by sergant210** [comment]
Реализовано в новой версии.
